export const activities = [
  {
    id: 1,
    name: "普罗米娅/卢西娅 - 限时频段",
    startWeek: 1,
    endWeek: 4,
    type: "red",
    icons: 2,
    hasDollarSign: true,
    hasCharIcon: true,
  },
  {
    id: 2,
    name: "星徽·比利/奥菲丝&「鬼火」- 限时频段",
    startWeek: 4,
    endWeek: 6,
    type: "red",
    icons: 2,
    hasDollarSign: true,
    hasCharIcon: true,
  },
  {
    id: 3,
    name: "游乐岛拯救计划",
    startWeek: 1,
    endWeek: 5,
    type: "orange",
    icons: 4,
    hasDollarSign: false,
    hasCharIcon: false,
  },
  {
    id: 4,
    name: "极限裁决试炼",
    startWeek: 2,
    endWeek: 4,
    type: "orange",
    icons: 2,
    hasDollarSign: false,
    hasCharIcon: false,
  },
  {
    id: 5,
    name: "「灵魂」画手侧写簿",
    startWeek: 4,
    endWeek: 6,
    type: "gray",
    icons: 3,
    hasDollarSign: false,
    hasCharIcon: false,
  },
];
